### PR TITLE
Refactor to use proptypes

### PR DESCRIPTION
**Pull request by srph**

### CODE REVIEW

**Comment by tj** [comment]
wonder if babel has static props so we can do `propTypes = ` inline, I'm generally not a fan of propTypes but that would make it less ugly

**Comment by srph** [comment]
[syntax-class-properties](http://babeljs.io/docs/plugins/syntax-class-properties/)

**Comment by tj** [comment]
might be in the stage-0 already with `static propTypes =`

**Comment by srph** [comment]
https://github.com/tj/react-click-outside/pull/3

**Pull request closed without merging**
